version: '3'

services:
  app13319:
    image: brentgroves/app13319:latest
    depends_on:
      - db
    container_name: app13319
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_HOSTNAME=db
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
#  There is an .env file in the React13319 folder.
#  Which is used during the npm run build step
#  The values at the time of the build will be hard coded into
#  js files.  During development the port value should be set to
#  3030 since we are debugging it from the React13319 folder by running
# npm start, but in production this app will
#  served up by the Feathers app so the port is set to 80,
#  since port 80 of the host machine is being mapped to port 3000
#  of the docker container
# THESE VARIABLES ARE ALSO USED IN THE Feathers.index.js files
# So we must uncomment them here for that reason.
      - REACT_APP_FEATHERS_HOSTNAME=$REACT_APP_FEATHERS_HOSTNAME
      - REACT_APP_FEATHERS_PORT=$REACT_APP_FEATHERS_PORT
      - MSSQL_USER=$MSSQL_USER
      - MSSQL_PASSWORD=$MSSQL_PASSWORD
      - MSSQL_DATABASE=$MSSQL_DATABASE
      - MSSQL_SERVER=$MSSQL_SERVER
    networks:
      - app-network
  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
