version: '3'

services:
  mqtt2:
    image: eclipse-mosquitto:1.6.10
    # Container params  
    restart: unless-stopped
    networks:
      - backend
    ports:
      # If host has a mosquitto server running we need to map to an alternate port
      # sudo ss -tulwn | grep LISTEN
      # HOST:CONTAINER
      - "1883:1883"
    volumes:
      - /etc/volumes/mosquitto:/mosquitto
    container_name: mqtt2

  mailer13319:
    # Wait for other containers
    depends_on:
      - mqtt2
    # Image params.  
    env_file: .env
    environment:
      - MQTT_SERVER=mqtt2
      - MQTT_PORT=$MQTT_PORT
      - NODE_ENV=$NODE_ENV
    command: sh -c "dockerize -wait tcp://mqtt2:1883 $NODE_CMD"
    build:
      context: ../mailer13319
    image: brentgroves/mailer13319:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/mailer13319:/usr/src/app
      - mailer_node_modules:/usr/src/app/node_modules      
    networks:
      - backend
    restart: unless-stopped
    container_name: mailer13319

  alarms13319:
    # Wait for other containers
    depends_on:
      - mqtt2
    # Image params.  
    env_file: .env
    environment:
      - MQTT_SERVER=mqtt2
      - MQTT_PORT=$MQTT_PORT
      - NODE_ENV=$NODE_ENV
    command: sh -c "dockerize -wait tcp://mqtt2:1883 $NODE_CMD"
    build:
      context: ../alarms13319
    image: brentgroves/alarms13319:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/alarms13319:/usr/src/app
      - alarms_node_modules:/usr/src/app/node_modules      
    networks:
      - backend
    restart: unless-stopped
    container_name: alarms13319


networks:
  backend:
    driver: bridge


volumes:
  alarms_node_modules:
  mailer_node_modules:
