version: '3'

services:
  db:
    # Image params.  
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0.19
    # Container params  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/volumes/mysql:/var/lib/mysql
      - /etc/volumes/mysql/conf.d:/etc/mysql/conf.d       
    networks:
      - backend
    ports:
      # This assumes a sql server is already running on the production server
      # This allows connection to it from the host using dbeaver
      # Should stop the host Mysql from booting at start up for better performance
      # HOST:CONTAINER
      - "3306:3306"
    restart: unless-stopped
    container_name: db

  mqtt2:
    image: eclipse-mosquitto:1.6.10
    # Container params  
    restart: unless-stopped
    networks:
      - backend
    ports:
      # If host has a mosquitto server running we need to map to an alternate port
      # sudo ss -tulwn | grep LISTEN
      # HOST:CONTAINER
      - "1883:1883"
    volumes:
      - /etc/volumes/mosquitto:/mosquitto
    restart: unless-stopped
    container_name: mqtt2

  eng13319api:
    # Wait for other containers
    depends_on:
      - db
      - mqtt2      
    # Image params.  
    env_file: .env
    environment:
      - KORS_USERNAME=$KORS_USERNAME
      - KORS_PASSWORD=$KORS_PASSWORD
      - KORS_DATABASE=$KORS_DATABASE
      - KORS_SERVER=$KORS_SERVER
      - MSSQL_USER=$MSSQL_USER
      - MSSQL_PASSWORD=$MSSQL_PASSWORD
      - MSSQL_DATABASE=$MSSQL_DATABASE
      - MSSQL_SERVER=$MSSQL_SERVER
      - FEATHERS_PORT=$FEATHERS_PORT
      - MQTT_SERVER=mqtt2
      - MQTT_PORT=$MQTT_PORT
      - MYSQL_HOSTNAME=db
      - MYSQL_PORT=$MYSQL_PORT 
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - VIRTUAL_HOST=$ENG_API_HOST
      - VIRTUAL_PORT=3030
    command: sh -c "dockerize -wait tcp://db:3306 -wait tcp://mqtt2:1883 -timeout 60s $NODE_CMD"
    build:
      context: ../eng13319api
    image: brentgroves/eng13319api:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/eng13319api:/usr/src/app
      - eng_api_node_modules:/usr/src/app/node_modules      
    networks:
      - backend
    restart: unless-stopped
    container_name: eng13319api

  tool13319api:
    # Wait for other containers
    depends_on:
      - db
      - mqtt2      
    # Image params.  
    env_file: .env
    environment:
      - KORS_USERNAME=$KORS_USERNAME
      - KORS_PASSWORD=$KORS_PASSWORD
      - KORS_DATABASE=$KORS_DATABASE
      - KORS_SERVER=$KORS_SERVER
      - MSSQL_USER=$MSSQL_USER
      - MSSQL_PASSWORD=$MSSQL_PASSWORD
      - MSSQL_DATABASE=$MSSQL_DATABASE
      - MSSQL_SERVER=$MSSQL_SERVER
      - FEATHERS_PORT=$FEATHERS_PORT
      - MQTT_SERVER=mqtt2
      - MQTT_PORT=$MQTT_PORT
      - MYSQL_HOSTNAME=db
      - MYSQL_PORT=$MYSQL_PORT 
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - VIRTUAL_HOST=$TOOL_API_HOST
      - VIRTUAL_PORT=3030
    command: sh -c "dockerize -wait tcp://db:3306 -wait tcp://mqtt2:1883 -timeout 60s $NODE_CMD"
    build:
      context: ../tool13319api
    image: brentgroves/tool13319api:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/tool13319api:/usr/src/app
      - tool_api_node_modules:/usr/src/app/node_modules      
    networks:
      - backend
    restart: unless-stopped
    container_name: tool13319api

  prod13319api:
    # Wait for other containers
    depends_on:
      - db
      - mqtt2      
    # Image params.  
    env_file: .env
    environment:
      - KORS_USERNAME=$KORS_USERNAME
      - KORS_PASSWORD=$KORS_PASSWORD
      - KORS_DATABASE=$KORS_DATABASE
      - KORS_SERVER=$KORS_SERVER
      - MSSQL_USER=$MSSQL_USER
      - MSSQL_PASSWORD=$MSSQL_PASSWORD
      - MSSQL_DATABASE=$MSSQL_DATABASE
      - MSSQL_SERVER=$MSSQL_SERVER
      - FEATHERS_PORT=$FEATHERS_PORT
      - MQTT_SERVER=mqtt2
      - MQTT_PORT=$MQTT_PORT
      - MYSQL_HOSTNAME=db
      - MYSQL_PORT=$MYSQL_PORT 
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - VIRTUAL_HOST=$PROD_API_HOST
      - VIRTUAL_PORT=3030
    command: sh -c "dockerize -wait tcp://db:3306 -wait tcp://mqtt2:1883 -timeout 60s $NODE_CMD"
    build:
      context: ../prod13319api
    image: brentgroves/prod13319api:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/prod13319api:/usr/src/app
      - prod_api_node_modules:/usr/src/app/node_modules      
    networks:
      - backend
    restart: unless-stopped
    container_name: prod13319api

  gm13319api:
    # Wait for other containers
    depends_on:
      - db
      - mqtt2      
    # Image params.  
    env_file: .env
    environment:
      - KORS_USERNAME=$KORS_USERNAME
      - KORS_PASSWORD=$KORS_PASSWORD
      - KORS_DATABASE=$KORS_DATABASE
      - KORS_SERVER=$KORS_SERVER
      - MSSQL_USER=$MSSQL_USER
      - MSSQL_PASSWORD=$MSSQL_PASSWORD
      - MSSQL_DATABASE=$MSSQL_DATABASE
      - MSSQL_SERVER=$MSSQL_SERVER
      - FEATHERS_PORT=$FEATHERS_PORT
      - MQTT_SERVER=mqtt2
      - MQTT_PORT=$MQTT_PORT
      - MYSQL_HOSTNAME=db
      - MYSQL_PORT=$MYSQL_PORT 
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - VIRTUAL_HOST=$GM_API_HOST
      - VIRTUAL_PORT=3030
    command: sh -c "dockerize -wait tcp://db:3306 -wait tcp://mqtt2:1883 -timeout 60s $NODE_CMD"
    build:
      context: ../gm13319api
    image: brentgroves/gm13319api:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/gm13319api:/usr/src/app
      - gm_api_node_modules:/usr/src/app/node_modules      
    networks:
      - backend
    restart: unless-stopped
    container_name: gm13319api

  tool13319:
    # Wait for other containers
    depends_on:
      - tool13319api
    # Image params.  
    env_file: .env
    environment:
      # - NODE_ENV=$NODE_ENV
      - VIRTUAL_HOST=$TOOL_PWA_HOST
      - VIRTUAL_PORT=3000
    # command: sh -c "$REACT_CMD"
    command: sh -c "dockerize -wait tcp://tool13319api:3030 -timeout 60s $PWA_CMD"
    build:
      context: ../tool13319
    image: brentgroves/tool13319:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/tool13319:/usr/src/app
      - tool_node_modules:/usr/src/app/node_modules      
      - tool_build:/usr/src/app/build      
    networks:
      - backend
      - frontend
    restart: unless-stopped
    container_name: tool13319

  eng13319:
    # Wait for other containers
    depends_on:
      - gm13319api
    # Image params.  
    env_file: .env
    environment:
      # - NODE_ENV=$NODE_ENV
      - VIRTUAL_HOST=$ENG_PWA_HOST
      - VIRTUAL_PORT=3000
    # command: sh -c "$REACT_CMD"
    command: sh -c "dockerize -wait tcp://eng13319api:3030 -timeout 60s $PWA_CMD"
    build:
      context: ../eng13319
    image: brentgroves/eng13319:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/eng13319:/usr/src/app
      - eng_node_modules:/usr/src/app/node_modules      
      - eng_build:/usr/src/app/build      
    networks:
      - backend
      - frontend
    restart: unless-stopped
    container_name: eng13319

  prod13319:
    # Wait for other containers
    depends_on:
      - prod13319api
    # Image params.  
    env_file: .env
    environment:
      # - NODE_ENV=$NODE_ENV
      - VIRTUAL_HOST=$PROD_PWA_HOST
      - VIRTUAL_PORT=3000
    # command: sh -c "$REACT_CMD"
    command: sh -c "dockerize -wait tcp://prod13319api:3030 -timeout 60s $PWA_CMD"
    build:
      context: ../prod13319
    image: brentgroves/prod13319:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/prod13319:/usr/src/app
      - prod_node_modules:/usr/src/app/node_modules      
      - prod_build:/usr/src/app/build      
    networks:
      - backend
      - frontend
    restart: unless-stopped
    container_name: prod13319

  gm13319:
    # Wait for other containers
    depends_on:
      - gm13319api
    # Image params.  
    env_file: .env
    environment:
      # - NODE_ENV=$NODE_ENV
      - VIRTUAL_HOST=$GM_PWA_HOST
      - VIRTUAL_PORT=3000
    # command: sh -c "$REACT_CMD"
    command: sh -c "dockerize -wait tcp://gm13319api:3030 -timeout 60s $PWA_CMD"
    build:
      context: ../gm13319
    image: brentgroves/gm13319:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/gm13319:/usr/src/app
      - gm_node_modules:/usr/src/app/node_modules      
      - gm_build:/usr/src/app/build      
    networks:
      - backend
      - frontend
    restart: unless-stopped
    container_name: gm13319

  alarms13319:
    # Wait for other containers
    depends_on:
      - mqtt2
    # Image params.  
    env_file: .env
    environment:
      - MQTT_SERVER=mqtt2
      - MQTT_PORT=$MQTT_PORT
      - NODE_ENV=$NODE_ENV
    command: sh -c "dockerize -wait tcp://mqtt2:1883 -timeout 60s $NODE_CMD"
    build:
      context: ../alarms13319
    image: brentgroves/alarms13319:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/alarms13319:/usr/src/app
      - alarms_node_modules:/usr/src/app/node_modules      
    networks:
      - backend
    restart: unless-stopped
    container_name: alarms13319

  mailer13319:
    # Wait for other containers
    depends_on:
      - db
      - mqtt2      
    # Image params.  
    env_file: .env
    environment:
      - MQTT_SERVER=mqtt2
      - MQTT_PORT=$MQTT_PORT
      - NODE_ENV=$NODE_ENV
    command: sh -c "dockerize -wait tcp://mqtt2:1883 -timeout 60s $NODE_CMD"
    # command: sh -c "dockerize -wait tcp://db:3306 -wait tcp://mqtt2:1883 $NODE_CMD"
    build:
      context: ../mailer13319
    image: brentgroves/mailer13319:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/mailer13319:/usr/src/app
      - mailer_node_modules:/usr/src/app/node_modules      
    networks:
      - backend
    restart: unless-stopped
    container_name: mailer13319

  nginx-proxy:
    # Wait for other containers
    depends_on:
      - eng13319
      - tool13319
      - prod13319
      - gm13319
      - eng13319api
      - tool13319api
      - prod13319api
      - gm13319api
    # Image params.  
    image: jwilder/nginx-proxy
    # Container params  
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/brent/srcnode/App13319/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      # nginx must communicate with php-fpm from the backend network
      - backend
    restart: unless-stopped
    container_name: nginx-proxy

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge


volumes:
  tool_node_modules:
  tool_api_node_modules:
  tool_build:
  eng_node_modules:
  eng_api_node_modules:
  eng_build:
  prod_node_modules:
  prod_api_node_modules:
  prod_build:
  gm_node_modules:
  gm_api_node_modules:
  gm_build:
  alarms_node_modules:
  mailer_node_modules:
