version: '3'

services:
  app13319:
    image: brentgroves/app13319:0.12
    depends_on:
      - db
    container_name: app13319
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_HOSTNAME=db
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MSSQL_USER=$MSSQL_USER
      - MSSQL_PASSWORD=$MSSQL_PASSWORD
      - MSSQL_DATABASE=$MSSQL_DATABASE
      - MSSQL_SERVER=$MSSQL_SERVER
      - KORS_USERNAME=$KORS_USERNAME
      - KORS_PASSWORD=$KORS_PASSWORD
      - KORS_DATABASE=$KORS_DATABASE
      - KORS_SERVER=$KORS_SERVER
      - FEATHERS_PORT=$FEATHERS_PORT
      - OPCUA_ENDPOINT=$OPCUA_ENDPOINT
      - MQTT_SERVER=mqtt2
      - PROD_WSDL=$PROD_WSDL
      - TEST_WSDL=$TEST_WSDL
      - ALBION_USER=$ALBION_USER
      - ALBION_PASSWORD=$ALBION_PASSWORD
      - AVILLA_USER=$AVILLA_USER
      - AVILLA_PASSWORD=$AVILLA_PASSWORD
      - MY_ENV=$MY_ENV
      - TZ=America/Fort_Wayne
    networks:
      - app-network
  db:
    image: mysql:8.0.19
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    networks:
      - app-network
  mqtt2:
    image: eclipse-mosquitto:1.6.10
    container_name: mqtt2
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
