version: '3'

services:
  app13319:
    ports:
      #  create-react-app is served by Feathers
      - "80:3030"
      #  Feathers is port 3030
      - "3030:3030"
    # Wait for mysql to start before running this app
    command: ["/wait-for-it.sh", "db:3306", "--", "/home/node/App13319/Docker13319/start-prod.sh"]
  db:
    ports:
      # This assumes a sql server is already running on the production server
      # This allows connection to it from the host using dbeaver
      # Should stop the host Mysql from booting at start up for better performance
      - "3305:3306"
    volumes:
      # don't know what the localtime binding is for?
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/volumes/mysql:/var/lib/mysql
      - /etc/volumes/mysql/conf.d:/etc/mysql/conf.d    
  mqtt2:
    ports:
      # If host has a mosquitto server running we need to map to an alternate port
      # sudo ss -tulwn | grep LISTEN
      - "1882:1883"
    volumes:
      - /etc/volumes/mosquitto:/mosquitto
