version: '3'

services:
  db:
    # Image params.  
    env_file: .env
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0.19
    # Container params  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/volumes/mysql:/var/lib/mysql
      - /etc/volumes/mysql/conf.d:/etc/mysql/conf.d       
    networks:
      - backend
    ports:
      # This assumes a sql server is already running on the production server
      # This allows connection to it from the host using dbeaver
      # Should stop the host Mysql from booting at start up for better performance
      # HOST:CONTAINER
      - "3306:3306"
    restart: unless-stopped
    container_name: db

  mqtt2:
    image: eclipse-mosquitto:1.6.10
    # Container params  
    restart: unless-stopped
    networks:
      - backend
    ports:
      # If host has a mosquitto server running we need to map to an alternate port
      # sudo ss -tulwn | grep LISTEN
      # HOST:CONTAINER
      - "1883:1883"
    volumes:
      - /etc/volumes/mosquitto:/mosquitto
    restart: unless-stopped
    container_name: mqtt2

  feat13319:
    # Wait for other containers
    depends_on:
      - db
      - mqtt2      
    # Image params.  
    env_file: .env
    environment:
      - KORS_USERNAME=$KORS_USERNAME
      - KORS_PASSWORD=$KORS_PASSWORD
      - KORS_DATABASE=$KORS_DATABASE
      - KORS_SERVER=$KORS_SERVER
      - MSSQL_USER=$MSSQL_USER
      - MSSQL_PASSWORD=$MSSQL_PASSWORD
      - MSSQL_DATABASE=$MSSQL_DATABASE
      - MSSQL_SERVER=$MSSQL_SERVER
      - FEATHERS_PORT=$FEATHERS_PORT
      - MQTT_SERVER=mqtt2
      - MQTT_PORT=$MQTT_PORT
      - MYSQL_HOSTNAME=db
      - MYSQL_PORT=$MYSQL_PORT 
      - MYSQL_USERNAME=$MYSQL_USERNAME
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - VIRTUAL_HOST=$WEBSERVICE_HOST
      - VIRTUAL_PORT=3030
    command: sh -c "dockerize -wait tcp://db:3306 -wait tcp://mqtt2:1883 $NODE_CMD"
    # command: sh -c "$FEATHERS_CMD"
    build:
      context: ../feat13319
    image: brentgroves/feat13319:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/feat13319:/usr/src/app
      - feat_node_modules:/usr/src/app/node_modules      
    networks:
      - backend
    restart: unless-stopped
    container_name: feat13319

  tool13319:
    # Wait for other containers
    depends_on:
      - feat13319
    # Image params.  
    env_file: .env
    environment:
      # - NODE_ENV=$NODE_ENV
      - VIRTUAL_HOST=$TOOL_PWA_HOST
      - VIRTUAL_PORT=3000
    # command: sh -c "$REACT_CMD"
    command: sh -c "dockerize -wait tcp://feat13319:3030 $PWA_CMD"
    build:
      context: ../tool13319
    image: brentgroves/tool13319:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/tool13319:/usr/src/app
      - tool_node_modules:/usr/src/app/node_modules      
      - tool_build:/usr/src/app/build      
    networks:
      - backend
      - frontend
    restart: unless-stopped
    container_name: tool13319

  eng13319:
    # Wait for other containers
    depends_on:
      - feat13319
    # Image params.  
    env_file: .env
    environment:
      # - NODE_ENV=$NODE_ENV
      - VIRTUAL_HOST=$ENG_PWA_HOST
      - VIRTUAL_PORT=3000
    # command: sh -c "$REACT_CMD"
    command: sh -c "dockerize -wait tcp://feat13319:3030 $PWA_CMD"
    build:
      context: ../eng13319
    image: brentgroves/eng13319:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/eng13319:/usr/src/app
      - eng_node_modules:/usr/src/app/node_modules      
      - eng_build:/usr/src/app/build      
    networks:
      - backend
      - frontend
    restart: unless-stopped
    container_name: eng13319

  prod13319:
    # Wait for other containers
    depends_on:
      - feat13319
    # Image params.  
    env_file: .env
    environment:
      # - NODE_ENV=$NODE_ENV
      - VIRTUAL_HOST=$PROD_PWA_HOST
      - VIRTUAL_PORT=3000
    # command: sh -c "$REACT_CMD"
    command: sh -c "dockerize -wait tcp://feat13319:3030 $PWA_CMD"
    build:
      context: ../prod13319
    image: brentgroves/prod13319:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/prod13319:/usr/src/app
      - prod_node_modules:/usr/src/app/node_modules      
      - prod_build:/usr/src/app/build      
    networks:
      - backend
      - frontend
    restart: unless-stopped
    container_name: prod13319

  alarms13319:
    # Wait for other containers
    depends_on:
      - mqtt2
    # Image params.  
    env_file: .env
    environment:
      - MQTT_SERVER=mqtt2
      - MQTT_PORT=$MQTT_PORT
      - NODE_ENV=$NODE_ENV
    command: sh -c "dockerize -wait tcp://mqtt2:1883 $NODE_CMD"
    build:
      context: ../alarms13319
    image: brentgroves/alarms13319:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/alarms13319:/usr/src/app
      - alarms_node_modules:/usr/src/app/node_modules      
    networks:
      - backend
    restart: unless-stopped
    container_name: alarms13319

  mailer13319:
    # Wait for other containers
    depends_on:
      - db
      - mqtt2      
    # Image params.  
    env_file: .env
    environment:
      - MQTT_SERVER=mqtt2
      - MQTT_PORT=$MQTT_PORT
      - NODE_ENV=$NODE_ENV
    command: sh -c "dockerize -wait tcp://mqtt2:1883 $NODE_CMD"
    # command: sh -c "dockerize -wait tcp://db:3306 -wait tcp://mqtt2:1883 $NODE_CMD"
    build:
      context: ../mailer13319
    image: brentgroves/mailer13319:1.0.0

    # Container params  
    stdin_open: true  
    volumes:
      # Sets the image and containers timezone to that of the host system
      - /etc/localtime:/etc/localtime:ro
      # must be absolute path
      - /home/brent/srcnode/App13319/mailer13319:/usr/src/app
      - mailer_node_modules:/usr/src/app/node_modules      
    networks:
      - backend
    restart: unless-stopped
    container_name: mailer13319

  nginx-proxy:
    # Wait for other containers
    depends_on:
      - eng13319
      - tool13319
      - prod13319
      - feat13319
    # Image params.  
    image: jwilder/nginx-proxy
    # Container params  
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/brent/srcnode/App13319/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend
      # nginx must communicate with php-fpm from the backend network
      - backend
    restart: unless-stopped
    container_name: nginx-proxy

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge


volumes:
  feat_node_modules:
  tool_node_modules:
  tool_build:
  eng_node_modules:
  eng_build:
  prod_node_modules:
  prod_build:
  alarms_node_modules:
  mailer_node_modules:
